CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	userName VARCHAR(100) NOT NULL,
	userEmail VARCHAR(200) NOT NULL UNIQUE,
	userPassword VARCHAR(100) NOT NULL
)

CREATE TABLE locations(
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	name VARCHAR(200) NOT NULL,
	longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
	latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90)
)